/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oopsystem;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aliha
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    ArrayList<Product> productList = new ArrayList();
    DefaultTableModel product_table_model;
    DefaultComboBoxModel order_model;
    ArrayList<cart> cart1 = new ArrayList();
    DefaultTableModel cart_model;
    
    // Create the table model
DefaultTableModel tableModel = new DefaultTableModel();


    public GUI() {
        initComponents();
        product_table_model = new DefaultTableModel();
        Products_table.setModel(product_table_model);
        
        order_model = new DefaultComboBoxModel();
        displayProductmodel.setModel(order_model);
        cart_model = new DefaultTableModel();
        
        cart_table.setModel(cart_model);
        cart_model.setColumnCount(3);
        this.cart_model.addColumn("Name");
        this.cart_model.addColumn("Price");
        this.cart_model.addColumn("Qunatity");
    
        
// Set the column names
tableModel.addColumn("ID");
tableModel.addColumn("Name");
tableModel.addColumn("Price");

// Set the model for the cart_table
cart_table.setModel(tableModel);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Main_Panel = new javax.swing.JPanel();
        Order = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        customer_name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        customer_id = new javax.swing.JTextField();
        displayProductmodel = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        display_price = new javax.swing.JLabel();
        stock = new javax.swing.JLabel();
        display_quantity = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        enter_quantity = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        cart_table = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        Sales_Assistant = new javax.swing.JPanel();
        Products = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        product_name = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        product_id = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        product_price = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        product_stock = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        Store = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Products_table = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        Main_Panel.setLayout(new java.awt.CardLayout());

        Order.setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel8.setText("Order");
        jPanel1.add(jLabel8);

        Order.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setMinimumSize(new java.awt.Dimension(200, 250));
        jPanel2.setPreferredSize(new java.awt.Dimension(200, 230));
        jPanel2.setLayout(new java.awt.GridLayout(12, 1));

        jLabel1.setText("Customer Name");
        jPanel2.add(jLabel1);

        customer_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customer_nameActionPerformed(evt);
            }
        });
        jPanel2.add(customer_name);

        jLabel2.setText("Customer ID");
        jPanel2.add(jLabel2);
        jPanel2.add(customer_id);

        displayProductmodel.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                displayProductmodelItemStateChanged(evt);
            }
        });
        displayProductmodel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayProductmodelActionPerformed(evt);
            }
        });
        jPanel2.add(displayProductmodel);

        jLabel3.setText("Price");
        jPanel2.add(jLabel3);

        display_price.setText("20");
        jPanel2.add(display_price);

        stock.setText("Stock_level");
        jPanel2.add(stock);

        display_quantity.setText("20");
        jPanel2.add(display_quantity);

        jLabel4.setText("Quantity");
        jPanel2.add(jLabel4);

        enter_quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enter_quantityActionPerformed(evt);
            }
        });
        jPanel2.add(enter_quantity);

        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        Order.add(jPanel2, java.awt.BorderLayout.LINE_START);

        jPanel3.setLayout(new java.awt.BorderLayout());

        cart_table.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cart_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(cart_table);

        jPanel3.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jButton2.setText("SAVE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, java.awt.BorderLayout.PAGE_END);

        Order.add(jPanel3, java.awt.BorderLayout.CENTER);

        Main_Panel.add(Order, "card5");

        javax.swing.GroupLayout Sales_AssistantLayout = new javax.swing.GroupLayout(Sales_Assistant);
        Sales_Assistant.setLayout(Sales_AssistantLayout);
        Sales_AssistantLayout.setHorizontalGroup(
            Sales_AssistantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 652, Short.MAX_VALUE)
        );
        Sales_AssistantLayout.setVerticalGroup(
            Sales_AssistantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        Main_Panel.add(Sales_Assistant, "card2");

        Products.setLayout(new java.awt.BorderLayout());

        jPanel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel7.setText("Products");
        jPanel4.add(jLabel7);

        Products.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 456, Short.MAX_VALUE)
        );

        Products.add(jPanel5, java.awt.BorderLayout.LINE_START);

        jPanel6.setLayout(new java.awt.GridLayout(5, 2));

        jLabel9.setText("Name");
        jPanel6.add(jLabel9);

        product_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                product_nameActionPerformed(evt);
            }
        });
        jPanel6.add(product_name);

        jLabel10.setText("ID");
        jPanel6.add(jLabel10);
        jPanel6.add(product_id);

        jLabel11.setText("Price");
        jPanel6.add(jLabel11);

        product_price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                product_priceActionPerformed(evt);
            }
        });
        jPanel6.add(product_price);

        jLabel12.setText("Stock");
        jPanel6.add(jLabel12);

        product_stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                product_stockActionPerformed(evt);
            }
        });
        jPanel6.add(product_stock);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 276, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 91, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel7);

        jButton3.setText("SAVE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton3);

        Products.add(jPanel6, java.awt.BorderLayout.CENTER);

        Main_Panel.add(Products, "card3");

        Store.setBackground(new java.awt.Color(153, 255, 204));
        Store.setLayout(new java.awt.CardLayout());

        Products_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "ID", "Price", "Stock"
            }
        ));
        jScrollPane1.setViewportView(Products_table);

        Store.add(jScrollPane1, "card2");

        Main_Panel.add(Store, "card3");

        getContentPane().add(Main_Panel, "card7");

        jMenu1.setText("File");

        jMenuItem1.setText("Sales Assistant");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Store");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem4.setText("Order");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem5.setText("ADD products");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void customer_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customer_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customer_nameActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
       this.Main_Panel.removeAll();
       this.Main_Panel.add(this.Products);
       this.Main_Panel.revalidate();
       this.Main_Panel.repaint();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void product_stockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_product_stockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_product_stockActionPerformed

    private void product_priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_product_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_product_priceActionPerformed

    private void product_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_product_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_product_nameActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        this.order_model.removeAllElements();
        this.Main_Panel.removeAll();
       this.Main_Panel.add(this.Order);
       this.Main_Panel.revalidate();
       this.Main_Panel.repaint();
       for(int i=0;i<this.productList.size();i++){
           this.order_model.addElement(productList.get(i));
       }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
         this.Main_Panel.removeAll();
       this.Main_Panel.add(this.Sales_Assistant);
       this.Main_Panel.revalidate();
       this.Main_Panel.repaint();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
         this.Main_Panel.removeAll();
       this.Main_Panel.add(this.Store);
       this.Main_Panel.revalidate();
       this.Main_Panel.repaint();
       
       // displaying products in Store:
       for(int i=0;i<this.productList.size();i++){
           this.product_table_model.setValueAt( productList.get(i).getName(), 0, i);
       }
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //Funtion performed on products:
        String Pname = product_name.getText();
         String Pid = product_id.getText();
          String Pprice = product_price.getText();
           String Pstock= product_stock.getText();
           
           Product pr = new Product(Pname,Integer.parseInt(Pid),Double.parseDouble(Pprice),Integer.parseInt(Pstock));
        
           productList.add(pr);
           JOptionPane.showMessageDialog(this,"Added");
           
           product_name.setText("");
           product_id.setText("");
           product_price.setText("");
           product_stock.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        Customer c1 = new Customer();
        c1.setName(customer_name.getText());
        c1.setId(Integer.parseInt(customer_id.getText()));
    }//GEN-LAST:event_jButton2ActionPerformed
/*
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        int index = displayProductmodel.getSelectedIndex();
        cart crt = new cart(productList.get(index),Integer.parseInt(enter_quantity.getText()));
        cart1.add(crt);
        
        this.cart_model.setRowCount(cart1.size());
        
       for(int i=0;i<cart1.size();i++){
           this.cart_model.setValueAt(cart1.get(i).getPr().getName(), 0, 0);
           this.cart_model.setValueAt(cart1.get(i).getPr().getPrice(), i, 1);
           this.cart_model.setValueAt(cart1.get(i).getPr().getQuantity(), i, 2);
       }
       
       productList.get(index).SetStock(productList.get(index).getStock() - Integer.parseInt(enter_quantity.getText()));
       // Assuming you have the product information in variables: productId, productName, productPrice

    // Get the table model
    DefaultTableModel tableModel = (DefaultTableModel) cart_table.getModel();

    // Create a new row with the product information
    Object[] row = {product_id, product_name, product_price};

    // Add the row to the table model
    tableModel.addRow(row);

    // Refresh the table to reflect the changes
    tableModel.fireTableDataChanged();

    }//GEN-LAST:event_jButton1ActionPerformed
*/
 private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
    
    int index = displayProductmodel.getSelectedIndex();
    cart crt = new cart(productList.get(index), Integer.parseInt(enter_quantity.getText()));
    cart1.add(crt);

    this.cart_model.setRowCount(cart1.size());

    for (int i = 0; i < cart1.size(); i++) {
        this.cart_model.setValueAt(cart1.get(i).getPr().getName(), i, 0);
        this.cart_model.setValueAt(cart1.get(i).getPr().getPrice(), i, 1);
        this.cart_model.setValueAt(cart1.get(i).getPr().getQuantity(), i, 2);
        this.cart_model.setValueAt(cart1.get(i).getQuantity(), i, 3); // Set selected quantity
    }

    productList.get(index).SetStock(productList.get(index).getStock() - Integer.parseInt(enter_quantity.getText()));

    // Get the product information from the cart object
    int product_id = crt.getPr().getId();
    String productName = crt.getPr().getName();
    double product_price = crt.getPr().getPrice();
    int product_quantity = crt.getQuantity();

    // Get the table model
    DefaultTableModel tableModel = (DefaultTableModel) cart_table.getModel();

    // Create a new row with the product information
    Object[] row = {product_id, productName, product_price, product_quantity};

    // Add the row to the table model
    tableModel.addRow(row);

    // Refresh the table to reflect the changes
    tableModel.fireTableDataChanged();
}


    private void displayProductmodelItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_displayProductmodelItemStateChanged
       
       int index =  displayProductmodel.getSelectedIndex();
        Product pro = productList.get(index);
        display_price.setText(pro.getPrice()+"");
        display_quantity.setText(pro.getStock()+"");
        
    }//GEN-LAST:event_displayProductmodelItemStateChanged

    private void enter_quantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enter_quantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enter_quantityActionPerformed

    private void displayProductmodelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayProductmodelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_displayProductmodelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Main_Panel;
    private javax.swing.JPanel Order;
    private javax.swing.JPanel Products;
    private javax.swing.JTable Products_table;
    private javax.swing.JPanel Sales_Assistant;
    private javax.swing.JPanel Store;
    private javax.swing.JTable cart_table;
    private javax.swing.JTextField customer_id;
    private javax.swing.JTextField customer_name;
    private javax.swing.JComboBox<String> displayProductmodel;
    private javax.swing.JLabel display_price;
    private javax.swing.JLabel display_quantity;
    private javax.swing.JTextField enter_quantity;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField product_id;
    private javax.swing.JTextField product_name;
    private javax.swing.JTextField product_price;
    private javax.swing.JTextField product_stock;
    private javax.swing.JLabel stock;
    // End of variables declaration//GEN-END:variables
}
