/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oopsystem;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aliha
 */
public class GUI1 extends javax.swing.JFrame {

    /**
     * Creates new form GUI1
     */
    ArrayList<Product>addProductlist = new ArrayList();
    DefaultTableModel store_t_model ;
    DefaultComboBoxModel order_combo;
    ArrayList<cart>cartlist = new ArrayList();
    DefaultTableModel cartTable;
    DefaultTableModel tableModel = new DefaultTableModel();
    public GUI1() {
        initComponents();
        store_t_model = new DefaultTableModel();
        Store_table.setModel(store_t_model);
        order_combo = new DefaultComboBoxModel();
        Order_box.setModel(order_combo);
        cartTable = new DefaultTableModel();
        order_table.setModel(cartTable);
        cartTable.setColumnCount(3);
        this.cartTable.addColumn("Name");
        this.cartTable.addColumn("Price");
        this.cartTable.addColumn("Qunatity");
    
        
        // Set the column names
        tableModel.addColumn("ID");
        tableModel.addColumn("Name");
        tableModel.addColumn("Price");

        // Set the model for the cart_table
        order_table.setModel(tableModel);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        MainPanel = new javax.swing.JPanel();
        store = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        Store_table = new javax.swing.JTable();
        Order = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        c_name = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        c_id = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        c_location = new javax.swing.JTextArea();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane12 = new javax.swing.JScrollPane();
        c_adress = new javax.swing.JTextArea();
        jLabel20 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        Order_box = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        display_price = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        display_stock = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        enter_quantity = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jScrollPane13 = new javax.swing.JScrollPane();
        order_table = new javax.swing.JTable();
        SalesAssistant = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        Products = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        product_name = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        product_id = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        product_price = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        product_stock = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.LINE_AXIS));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        jLabel5.setText("                              ADD Products");
        jPanel6.add(jLabel5);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        MainPanel.setLayout(new java.awt.CardLayout());

        store.setLayout(new java.awt.BorderLayout());

        jLabel12.setBackground(new java.awt.Color(255, 102, 102));
        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel12.setText("               Store");
        jLabel12.setOpaque(true);
        store.add(jLabel12, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        Store_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "ID", "Price", "Stock Level"
            }
        ));
        jScrollPane8.setViewportView(Store_table);

        jPanel1.add(jScrollPane8);

        store.add(jPanel1, java.awt.BorderLayout.CENTER);

        MainPanel.add(store, "card7");

        Order.setLayout(new java.awt.BorderLayout());

        jLabel13.setBackground(new java.awt.Color(0, 204, 204));
        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel13.setText("                           Process Order");
        jLabel13.setOpaque(true);
        Order.add(jLabel13, java.awt.BorderLayout.PAGE_START);

        jPanel9.setLayout(new java.awt.GridLayout(6, 0));

        jLabel14.setBackground(new java.awt.Color(255, 153, 153));
        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel14.setText("                  Customer Info");
        jLabel14.setOpaque(true);
        jPanel9.add(jLabel14);

        jLabel19.setBackground(new java.awt.Color(255, 153, 153));
        jLabel19.setOpaque(true);
        jPanel9.add(jLabel19);

        jLabel18.setText("Name");
        jPanel9.add(jLabel18);

        c_name.setColumns(20);
        c_name.setRows(5);
        jScrollPane9.setViewportView(c_name);

        jPanel9.add(jScrollPane9);

        jLabel15.setText("ID");
        jPanel9.add(jLabel15);

        c_id.setColumns(20);
        c_id.setRows(5);
        jScrollPane10.setViewportView(c_id);

        jPanel9.add(jScrollPane10);

        jLabel16.setText("Store location");
        jPanel9.add(jLabel16);

        c_location.setColumns(20);
        c_location.setRows(5);
        jScrollPane11.setViewportView(c_location);

        jPanel9.add(jScrollPane11);

        jLabel17.setText("Adress");
        jPanel9.add(jLabel17);

        c_adress.setColumns(20);
        c_adress.setRows(5);
        jScrollPane12.setViewportView(c_adress);

        jPanel9.add(jScrollPane12);
        jPanel9.add(jLabel20);

        jButton3.setText("ADD");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton3);

        Order.add(jPanel9, java.awt.BorderLayout.LINE_START);

        jPanel10.setLayout(new javax.swing.BoxLayout(jPanel10, javax.swing.BoxLayout.LINE_AXIS));

        jPanel2.setLayout(new java.awt.GridLayout(9, 0));

        jLabel21.setBackground(new java.awt.Color(255, 102, 102));
        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel21.setText("Select Products:");
        jLabel21.setOpaque(true);
        jPanel2.add(jLabel21);

        Order_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        Order_box.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Order_boxItemStateChanged(evt);
            }
        });
        jPanel2.add(Order_box);

        jLabel22.setText("Price");
        jPanel2.add(jLabel22);
        jPanel2.add(display_price);

        jLabel23.setText("Stock");
        jPanel2.add(jLabel23);
        jPanel2.add(display_stock);

        jLabel24.setText("Enter Qunatity");
        jPanel2.add(jLabel24);

        enter_quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enter_quantityActionPerformed(evt);
            }
        });
        jPanel2.add(enter_quantity);

        jButton4.setText("Select");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);

        jPanel10.add(jPanel2);

        order_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane13.setViewportView(order_table);

        jPanel10.add(jScrollPane13);

        Order.add(jPanel10, java.awt.BorderLayout.CENTER);

        MainPanel.add(Order, "card5");

        SalesAssistant.setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 51));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setText("                          Sales Assistant Info:");
        jLabel1.setOpaque(true);
        SalesAssistant.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBackground(new java.awt.Color(255, 255, 102));
        jPanel3.setLayout(new java.awt.GridLayout(7, 0));

        jLabel2.setBackground(new java.awt.Color(51, 153, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Name:");
        jLabel2.setOpaque(true);
        jPanel3.add(jLabel2);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel3.add(jScrollPane1);

        jLabel3.setBackground(new java.awt.Color(51, 153, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("ID:");
        jLabel3.setOpaque(true);
        jPanel3.add(jLabel3);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jPanel3.add(jScrollPane2);

        jLabel4.setBackground(new java.awt.Color(51, 153, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Store Location:");
        jLabel4.setOpaque(true);
        jPanel3.add(jLabel4);

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        jPanel3.add(jScrollPane3);

        jPanel5.setBackground(new java.awt.Color(255, 255, 0));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 96, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel5);

        jButton1.setBackground(new java.awt.Color(29, 165, 137));
        jButton1.setText("ENTER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);

        SalesAssistant.add(jPanel3, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 672, Short.MAX_VALUE)
        );

        SalesAssistant.add(jPanel4, java.awt.BorderLayout.LINE_END);

        MainPanel.add(SalesAssistant, "card2");

        Products.setLayout(new java.awt.BorderLayout());

        jLabel6.setBackground(new java.awt.Color(255, 153, 0));
        jLabel6.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        jLabel6.setText("                              ADD Products:");
        jLabel6.setOpaque(true);
        Products.add(jLabel6, java.awt.BorderLayout.PAGE_START);

        jPanel7.setLayout(new java.awt.GridLayout(8, 0));

        jLabel7.setBackground(new java.awt.Color(255, 204, 153));
        jLabel7.setText("Name:");
        jLabel7.setOpaque(true);
        jPanel7.add(jLabel7);

        product_name.setColumns(20);
        product_name.setRows(5);
        jScrollPane4.setViewportView(product_name);

        jPanel7.add(jScrollPane4);

        jLabel8.setBackground(new java.awt.Color(255, 204, 153));
        jLabel8.setText("ID:");
        jLabel8.setOpaque(true);
        jPanel7.add(jLabel8);

        product_id.setColumns(20);
        product_id.setRows(5);
        jScrollPane5.setViewportView(product_id);

        jPanel7.add(jScrollPane5);

        jLabel9.setBackground(new java.awt.Color(255, 204, 153));
        jLabel9.setText("Price:");
        jLabel9.setOpaque(true);
        jPanel7.add(jLabel9);

        product_price.setColumns(20);
        product_price.setRows(5);
        jScrollPane6.setViewportView(product_price);

        jPanel7.add(jScrollPane6);

        jLabel10.setBackground(new java.awt.Color(255, 204, 153));
        jLabel10.setText("Stock_level:");
        jLabel10.setOpaque(true);
        jPanel7.add(jLabel10);

        product_stock.setColumns(20);
        product_stock.setRows(5);
        jScrollPane7.setViewportView(product_stock);

        jPanel7.add(jScrollPane7);
        jPanel7.add(jLabel11);

        jButton2.setBackground(new java.awt.Color(102, 0, 0));
        jButton2.setText("ADD");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton2);

        Products.add(jPanel7, java.awt.BorderLayout.CENTER);

        MainPanel.add(Products, "card3");

        getContentPane().add(MainPanel, "card6");

        jMenu1.setText("Order");

        jMenuItem1.setText("Sales Assistant");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Product");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Store");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Order");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("BackOrder");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.MainPanel.removeAll();
        this.MainPanel.add(this.SalesAssistant);
        this.MainPanel.revalidate();
        this.MainPanel.repaint();
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       //order 
       Customer c = new Customer();
       c.setName(c_name.getText());
       c.setId(Integer.parseInt(c_id.getText()));
       c.setStore_loc(c_location.getText());
       c.setAdress(c_adress.getText());
       
       
       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        
        this.MainPanel.removeAll();
        this.MainPanel.add(this.Products);
        this.MainPanel.revalidate();
        this.MainPanel.repaint();
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        this.MainPanel.removeAll();
        this.MainPanel.add(this.store);
        this.MainPanel.revalidate();
        this.MainPanel.repaint();
        
        this.store_t_model.setColumnCount(4);
        this.store_t_model.setRowCount(addProductlist.size());
        this.store_t_model.setColumnIdentifiers(new String[]{"Name",  "ID","Price", "Stock"});
        //show table model
        for(int i=0 ; i<addProductlist.size() ; i++){
            this.store_t_model.setValueAt(addProductlist.get(i).getName(), i, 0);
            this.store_t_model.setValueAt(addProductlist.get(i).getId(), i, 1);
            this.store_t_model.setValueAt(addProductlist.get(i).getPrice(), i, 2);
            this.store_t_model.setValueAt(addProductlist.get(i).getStock(), i, 3);
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        this.order_combo.removeAllElements();
        this.MainPanel.removeAll();
        this.MainPanel.add(this.Order);
        this.MainPanel.revalidate();
        this.MainPanel.repaint();
        
        //combo
        this.order_combo.addElement("Select Product");
        for(int i=0;i<addProductlist.size();i++){
            this.order_combo.addElement(addProductlist.get(i));
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //adding product in add product:
        //Product 
        String p_name = product_name.getText();
        String p_id = product_price.getText();
        String p_price = product_price.getText();
        String p_stock = product_stock.getText();
        
        Product p1 = new Product(p_name,Integer.parseInt(p_id),Double.parseDouble(p_price),Integer.parseInt(p_stock));
        
        addProductlist.add(p1);
       JOptionPane.showMessageDialog(this, "Product added");
        
       product_name.setText("");
       product_price.setText("");
       product_id.setText("");
       product_stock.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int index = this.Order_box.getSelectedIndex();
        cart crt = new cart(addProductlist.get(index), Integer.parseInt(display_stock.getText()));
        cartlist.add(crt);

        this.cartTable.setRowCount(cartlist.size());

    for (int i = 0; i < cartlist.size(); i++) {
        this.cartTable.setValueAt(cartlist.get(i).getPr().getName(), i, 0);
        this.cartTable.setValueAt(cartlist.get(i).getPr().getPrice(), i, 1);
        this.cartTable.setValueAt(cartlist.get(i).getPr().getQuantity(), i, 2);
        this.cartTable.setValueAt(cartlist.get(i).getQuantity(), i, 3); // Set selected quantity
    }

    addProductlist.get(index).SetStock(addProductlist.get(index).getStock() - Integer.parseInt(display_stock.getText()));

    // Get the product information from the cart object
    int product_id = crt.getPr().getId();
    String productName = crt.getPr().getName();
    double product_price = crt.getPr().getPrice();
    int product_quantity = crt.getQuantity();

    // Get the table model
    DefaultTableModel tableModel = (DefaultTableModel) order_table.getModel();

    // Create a new row with the product information
    Object[] row = {product_id, productName, product_price, product_quantity};

    // Add the row to the table model
    tableModel.addRow(row);

    // Refresh the table to reflect the changes
    tableModel.fireTableDataChanged();
        
   
    }//GEN-LAST:event_jButton4ActionPerformed

    private void enter_quantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enter_quantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enter_quantityActionPerformed

    private void Order_boxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Order_boxItemStateChanged
     int index =  Order_box.getSelectedIndex();
        Product pro = addProductlist.get(index);
        display_price.setText(pro.getPrice()+"");
        display_stock.setText(pro.getStock()+"");
    }//GEN-LAST:event_Order_boxItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel Order;
    private javax.swing.JComboBox<String> Order_box;
    private javax.swing.JPanel Products;
    private javax.swing.JPanel SalesAssistant;
    private javax.swing.JTable Store_table;
    private javax.swing.JTextArea c_adress;
    private javax.swing.JTextArea c_id;
    private javax.swing.JTextArea c_location;
    private javax.swing.JTextArea c_name;
    private javax.swing.JLabel display_price;
    private javax.swing.JLabel display_stock;
    private javax.swing.JTextField enter_quantity;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTable order_table;
    private javax.swing.JTextArea product_id;
    private javax.swing.JTextArea product_name;
    private javax.swing.JTextArea product_price;
    private javax.swing.JTextArea product_stock;
    private javax.swing.JPanel store;
    // End of variables declaration//GEN-END:variables
}
